# Pytorch Fundamentals
* Notebook by Adam Lang
* Date: 1/26/2025

# Overview
* This notebook is based on the concepts taught in Daniel Bourke's PyTorch for Deep Learning Bootcamp on Udemy.
* Although I have been coding in PyTorch since 2022, I continually review and brush up on my torch skills and Daniel is the best in the business at teaching tips and tricks to make you a PyTorch guru. As the great Kobe Bryant once said:
```
Mamba Mentality means "to constantly try to be the best version of yourself.It's a constant quest to try to better today than you were yesterday."
```
```
“Why do you think I’m the best player in the world? Because I never ever get bored with the basics.”
```


# Import Dependencies

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
print(torch.__version__)

2.5.1+cu121


# Tensors in Pytorch

## Creating Tensors
* Tensor types in torch: https://pytorch.org/docs/stable/tensors.html

### 1. Scalar
* 1 dimension
* Usually lower case

In [ ]:
## 1. Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
## dimensions
scalar.ndim

0

In [ ]:
## get tensor back to integer
scalar.item()

7

### 2. Vector
* More than 1 dimension
* Usually lower case

In [ ]:
## 2. Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
## dimensions
vector.ndim

1

In [ ]:
## shape
vector.shape

torch.Size([2])

### 3. Matrix
* 2 dimensions
* Usually UPPER CASE

In [ ]:
## 3. matrix
MATRIX = torch.tensor([[7,8],
                      [10,11]])

MATRIX

tensor([[ 7,  8],
        [10, 11]])

In [ ]:
## dims
MATRIX.ndim

2

In [ ]:
## matrix shape
MATRIX.shape

torch.Size([2, 2])

In [ ]:
## index matrix
MATRIX[:,1]

tensor([ 8, 11])

### 4. Tensors
* 3 dimensional matrices!
* Ususally UPPER CASE

In [ ]:
## tensors
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
## dims
TENSOR.ndim

3

In [ ]:
## tensor shape
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
## 0th dim
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Tensor Practice
* Create random tensors

In [ ]:
## random tensors
rand_tensor = torch.tensor([[[1,2,3],
                             [10,11,12],
                             [14,16,18]]])

rand_tensor

tensor([[[ 1,  2,  3],
         [10, 11, 12],
         [14, 16, 18]]])

In [ ]:
## dims of rand tensor
rand_tensor.ndim

3

In [ ]:
## shape rand tensor
rand_tensor.shape

torch.Size([1, 3, 3])

### Random Tensors
* Why do we need random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers then adjust those random numbers to better represent the data.

Neural Networks in a nutshell:
```
Start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers
```
* Torch random tensors: https://pytorch.org/docs/main/generated/torch.rand.html

In [ ]:
10 * 10 * 10

1000

In [ ]:
## create random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1506, 0.3375, 0.1917, 0.1834],
        [0.0933, 0.7754, 0.3408, 0.9039],
        [0.8638, 0.8979, 0.2614, 0.3725]])

In [ ]:
## dims
random_tensor.ndim

2

In [ ]:
## shape
random_tensor.shape

torch.Size([3, 4])

In [ ]:
## Create random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)

## shape and ndim
print(f"Shape of random image tensor: {random_image_size_tensor.shape}\n\n")
print(f"Dimensions of random image tensor: {random_image_size_tensor.ndim}")

Shape of random image tensor: torch.Size([224, 224, 3])


Dimensions of random image tensor: 3


#### Random Tensor Practice
* create rand tensors!

In [ ]:
my_random_tensor = torch.rand([2,4,6])
my_random_tensor

tensor([[[0.2376, 0.8208, 0.4165, 0.0058, 0.6416, 0.5030],
         [0.0718, 0.2955, 0.5074, 0.4593, 0.2201, 0.6107],
         [0.4237, 0.2937, 0.6796, 0.3577, 0.3096, 0.7438],
         [0.7190, 0.6426, 0.0073, 0.9308, 0.9614, 0.6722]],

        [[0.4900, 0.7025, 0.1854, 0.3868, 0.8282, 0.6804],
         [0.0835, 0.0784, 0.8339, 0.7201, 0.1546, 0.7524],
         [0.7293, 0.1648, 0.8977, 0.6936, 0.4181, 0.5441],
         [0.1542, 0.2171, 0.8443, 0.5611, 0.1149, 0.1311]]])

In [ ]:
## ndim of tensor
my_random_tensor.ndim

3

In [ ]:
## shape of tensor
my_random_tensor.shape

torch.Size([2, 4, 6])

In [ ]:
### another random tensor
my_rand_2 = torch.rand(size=(3,3))
my_rand_2

tensor([[0.0649, 0.7584, 0.0997],
        [0.7070, 0.2699, 0.4671],
        [0.3376, 0.8205, 0.4959]])

### Zeros and Ones - Tensors
* just like in numpy we can create tensors of all zeros or all ones.

* Tensor of all zeros is helpful with masks.

In [ ]:
## 1. tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
## multiply by zeros
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

* Anything times zero is zero!

In [ ]:
## 2. Tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
## whats the dtype
ones.dtype

torch.float32

In [ ]:
## whats the dtype
zeros.dtype

torch.float32

In [ ]:
## whats the dtype
random_tensor.dtype

torch.float32

#### Zeros and Ones Practice

In [ ]:
## zeros
zeros_p = torch.zeros(size=(10,10))
zeros_p

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
## experiment
zeros_p = torch.zeros(size=(10,10), dtype=torch.float16)
zeros_p

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float16)

### Creating a range of tensors and tensors-like

In [ ]:
## use torch.arange() don't use torch.range it is deprecated
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.__version__

'2.5.1+cu121'

In [ ]:
### creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Torch range and torch-like practice

In [ ]:
one_to_fifty = torch.arange(start=1, end=51, step=1)
one_to_fifty

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
## zeros_like
fifty_zeros = torch.zeros_like(input=one_to_fifty)
fifty_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

### Tensor Data types
* Most common tensor params:
1. dtype --> defalt is float32
2. device
3. requires_grad


* Larger bits = more precision
* Smaller bits = less precision
  * Smaller bits is what we do when we quantize or perform quantization!

**Note**: 3 big errors in deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
## float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what dtype is tensor (float32, float16, etc.)
                               device=None, # default CPU vs. GPU
                               requires_grad=False) #if gradients are tracked or not
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

Summary
* Default dtype in pytorch is `float32`

In [ ]:
## change dtype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
## change back?
float_32_tensor = float_16_tensor.type(torch.float32)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
## multiple float_16 by float_32
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
##int 32 tensor
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors ("tensor attributes")

1. Tensors not right data type
  * use `tensor.dtype`

2. Tensors not right shape
  * use `tensor.shape`

3. Tensors not right device
  * use `tensor.device`

In [ ]:
## create tensor
some_tensor = torch.rand([3,4])
some_tensor

tensor([[0.8868, 0.9088, 0.7945, 0.4031],
        [0.8781, 0.1938, 0.8775, 0.9947],
        [0.9063, 0.0952, 0.4710, 0.0604]])

In [ ]:
## details about this tensor
print(some_tensor)
print()
print(f"Data type of tensor: {some_tensor.dtype}\n\n")
print(f"Shape of tensor: {some_tensor.shape}\n\n")
print(f"Device of tensor: {some_tensor.device}\n\n")

tensor([[0.8868, 0.9088, 0.7945, 0.4031],
        [0.8781, 0.1938, 0.8775, 0.9947],
        [0.9063, 0.0952, 0.4710, 0.0604]])

Data type of tensor: torch.float32


Shape of tensor: torch.Size([3, 4])


Device of tensor: cpu




#### Tensor attribute practice


In [ ]:
new_tensor = torch.tensor([10,10,10],dtype=torch.long)
new_tensor

tensor([10, 10, 10])

In [ ]:
new_tensor.dtype

torch.int64

In [ ]:
my_tensor = torch.rand([4,6]).type(torch.int32)
my_tensor

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
## shape
my_tensor.shape
my_tensor.dtype

torch.int32

### Manipulating Tensors (tensor operations)

* Tensor operations include:

1. addition
2. subtraction
3. multiplication (element-wise)
4. division
5. matrix multiplication (matmul)

In [ ]:
## create tensor --> ADD 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
## multiply 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
## subtract 10
tensor

tensor([1, 2, 3])

In [ ]:
## subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
## pytorch inbuilt functions --> "mul" is multiply
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [ ]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplication

* There are 2 main ways of performing multiplication in neural networks and deep learning

1. Element wise multiplication
2. Matrix multiplication (most common operation inside neural networks)


THERE ARE TWO MAIN RULES THAT PERFORMING MATRIX MULTIPLICATION NEEDS TO SATISFY:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` --> won't work!!
* `(2,3) @ (3,2)` --> WORKS!
* `(3,2) @ (2,3)` --> WORKS!

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` --> `(2,2)`
* `(3,2) @ (2,3)` --> `(3,3)`

In [ ]:
## example of inner dimensions -- inner dims must match!
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.2972, 0.7092],
        [0.9732, 0.9287]])

In [ ]:
## experiment
torch.matmul(torch.rand(3,10), torch.rand(10,7)).shape

torch.Size([3, 7])

In [ ]:
## Element wise multiplication
print(tensor , "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix mul --> dot product
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
## matrix mul by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.48 ms, sys: 0 ns, total: 2.48 ms
Wall time: 5.48 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 128 µs, sys: 0 ns, total: 128 µs
Wall time: 142 µs


tensor(14)

### One of most common errors in deep learning: SHAPE ERRORS

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])



In [ ]:
## check shapes
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
## matrix mul
torch.matmul(tensor_A, tensor_B) ## torch.mm is same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
## original
tensor_B.shape

torch.Size([3, 2])

In [ ]:
## transpose
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
## matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <-- inner dims must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <-- inner dims must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Summary
* If we transpose so the inner dimensions match then we can perform matrix multiplication.

### Finding the min, max, mean, sum, etc. (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
## min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
## max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
## mean
x.dtype

torch.int64

Summary
* Tensor we created is `int64` or Long, this does not work with `torch.mean()`
* We need to change dtype to `float32`

In [ ]:
## mean with converting type to float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
## sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Find positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
## argument min index
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
## argument max index
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Reshaping, stacking, squeezing and unsqueezing tensors
* The purpose is to manipulate tensor shape and dimensions for mathematical computations.

1. Reshaping
  * reshapes an input tensor to a defined shape.

2. View
  * returns a "view" of an input tensor of certain shape but keeps the **same memory as the original tensor.**

3. Stacking
  * combines multiple tensors on top of one another.
  * `torch.vstack()` -- vertical
  * `torch.hstack()` -- horizontal

4. Squeeze
  * removes all `1` dimensions from a tensor.
  * Removes the tensor "columns".

5. Unsqueeze
  * adds a `1` dimension to target tensor.
  * Expands the tensor "columns".

6. Permute
  * Return a view of the input with dimensions permuted (swapped in a certain way).

### Reshaping
* Reshape has to be compatible with original size

In [ ]:
## lets create a tensor
import torch
x = torch.arange(1.,10,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
## 1. reshape -- add extra dimension
x_reshaped = x.reshape(1,9) ## has to be compatible with torch.shape/size
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

### View
* View shares same memory as original tensor or original input.

In [ ]:
## change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### Stack Tensors
* Default is 0 --> horizontal
* 1 is vertical

In [ ]:
## stacking tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0) ## default dim is 0
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
## vstack -- adds them in a vertical bar stack
x_vstacked = torch.vstack([x,x,x,x,x,x,x,])
x_vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
## hstack --> adds them in a horizontal row
x_hstacked = torch.hstack([x,x,x,x,x,x,x,])
x_hstacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9.])

### Squeeze and Unsqueeze

In [ ]:
## torch.squeeze() -- removes all single dimensions from target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
### torch.unsqueeze -- adds single dim to target tensor at specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## unsqueeze it -- add extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0) ## 1 is vertical, 0 is horizontal
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


### Permute
* Rerranges dim of target tensor in specified order.
* Returns a view of the original tensor input with its dimensions permuted (rerranged).



In [ ]:
## torch.permute() --- common with image manipulation
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# permute original tensor to rearrange axis or dim order
x_permute = x_original.permute(2,0,1) ## shifts axis 0 to 1, 1-->2, 2-->0


print(f"Previous shape: {x_original.shape}\n\n")
print(f"New shape: {x_permute.shape}")

Previous shape: torch.Size([224, 224, 3])


New shape: torch.Size([3, 224, 224])


In [ ]:
## change val in x_oriinal
x_original[0,0,0] = 7092949
x_original[0,0,0], x_permute[0,0,0]

(tensor(7092949.), tensor(7092949.))

## Indexing - selecting data from tensors
* Indexing with tensors is very similar to numpy indexing.

In [ ]:
## create tensor
import torch

## arange tensor --> reshape it
x = torch.arange(1, 10).reshape(1,3,3) ## reshape factor of 9
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
## index on x tensor --> 0th dim or 1st bracket
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
## index on middle bracket
x[0,0]

tensor([1, 2, 3])

In [ ]:
## index on most inner bracket --> last dim
x[:,2,2]

tensor([9])

In [ ]:
## get all values of 0th and 1st dims but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
## get all vals of 0 dim but only 1 index val of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
## get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
## index on x to return 9
x[:,2,2]

tensor([9])

In [ ]:
## index on x to return 3, 6, 9
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## PyTorch Tensors & NumPy
* PyTorch has functionality to interact with NumPy.
* Data in numpy array but want in pytorch tensor.
  * method: `torch.from_numpy(ndarray)`
* From pytorch tensor to numpy
  * method: `torch.Tensor.numpy()`

In [ ]:
## numpy array ---> tensor
import torch
import numpy as np

## create array
array = np.arange(1.0, 8.0)

## np.array --> torch.tensor
tensor = torch.from_numpy(array)

## lets see both
print(f"array: {array}\n\n")
print(f"tensor: {tensor}\n\n")

array: [1. 2. 3. 4. 5. 6. 7.]


tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)




In [ ]:
## numpy's default dtype is float64
array.dtype

dtype('float64')

In [ ]:
## torch dtype
torch.dtype

torch.dtype

In [ ]:
## whats pytorch default dtype
torch.arange(1.0,8.0).dtype

torch.float32

Summary
* numpy default is float64
* torch default dtype is float32

In [ ]:
## change dtype?
array = np.arange(1.0, 8.0)
## to tensor
tensor = torch.from_numpy(array).type(torch.float32)
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
## change val of array -- what do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
## tensor --> numpy (`.numpy()`)
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
## change tensor, what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility
* trying to take the random out of random!
* In short how a neural network learns:
```
start with random numbers --> tensor operations --> update random numbers to try and make better representations of data --> again --> again --> again
```
* To reduce randomness in neural networks and pytorch, comes the concept of a **Random Seed**.

* Essentially, what the random seed does is "flavor" the randomness.

In [ ]:
## demo of rand
torch.rand(4,5)

tensor([[0.0913, 0.3055, 0.2284, 0.3211, 0.7395],
        [0.0705, 0.5477, 0.9304, 0.2702, 0.7833],
        [0.5925, 0.1439, 0.6490, 0.5648, 0.5010],
        [0.0796, 0.6883, 0.4191, 0.3414, 0.6212]])

In [ ]:
import torch

## create 2 random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9162, 0.9174, 0.4229, 0.0848],
        [0.1030, 0.8341, 0.2844, 0.6213],
        [0.9712, 0.8175, 0.5421, 0.0728]])
tensor([[0.2256, 0.1158, 0.6017, 0.2159],
        [0.1027, 0.6178, 0.1451, 0.2055],
        [0.2073, 0.1643, 0.4225, 0.5254]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
## lets make some random but reproducbible tensors
import torch

## set random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

## random tensor 1
random_tensor_c = torch.rand(3,4)

## random tensor 2 -- set random seed
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)


print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Summary
* Random seeds work well when they are placed or seeded directly before a line of code or tensor creation.

## Running tensors and PyTorch objects on GPUs and making faster computations

* GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything "hunky dory"

### 1. Getting a GPU

1. Easiest - Use Google colab for a free GPU -- or pro version

2. Use your own GPU -- investment!
  * see this blog: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/

3. Cloud
  * AWS
  * Azure


For 2, 3 PyTorch + GPU (CUDA) drivers refer to pytorch setup docs.



### 2. Check for GPU on PyTorch

In [ ]:
## check for gpu access on pytorch
import torch

torch.cuda.is_available()

False

### 3. Device agnostic code
* See cuda semantics: https://pytorch.org/docs/stable/notes/cuda.html

In [ ]:
# setup device agnostic code
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [ ]:
## count number of gpu devices you have
torch.cuda.device_count()

0

## Putting Tensors and models on GPU
* Putting these on the GPU results in faster computations.

In [ ]:
## create tensor -- default always cpu
tensor = torch.tensor([1,2,3])

## tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
## move tensor to gpu if available -- will show gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

## Moving Tensors back to CPU

In [ ]:
# if tensor on GPU cant transform to numpy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
# to fix gpu tensor with numpy issue first set it to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3])

## Set Seed on GPU

In [ ]:
# Set random seed on the GPU
import torch

seed = 42

# Set the random seed for PyTorch CPU operations
torch.manual_seed(seed)

# If you are using CUDA, set the random seed for GPU operations
if torch.cuda.is_available():
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed) # If you are using multiple GPUs

# Set the deterministic flag for CuDNN (for deterministic behavior in some operations)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False