# 00. PyTorch Fundamentals Exercises
* Notebook completed by Adam Lang as a fundamentals review of PyTorch from the great Daniel Bourke's PyTorch for Deep Learning bootcamp.

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch


# Create random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6166, 0.1430, 0.7448, 0.1084],
        [0.2052, 0.5265, 0.3747, 0.6748],
        [0.9046, 0.8960, 0.7379, 0.2403]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_2 = torch.rand(3,4)
random_tensor_2


## get shapes of tensors
print(f"Shape of random_tensor: {random_tensor.shape}")
print(f"Shape of random_tensor_2: {random_tensor_2.shape}")

Shape of random_tensor: torch.Size([3, 4])
Shape of random_tensor_2: torch.Size([3, 4])


We have 2 tensors: `(3,4)` and `(3,4`)

In order to matmul them we need to flip 1 so the inner dimensions match so we would get: `(3,4)` and (`4,3`)

The resulting shape should then be 3,3 the outer dimension

In [ ]:
## create transposed tensor
trans_tensor = random_tensor.T
trans_tensor.shape

torch.Size([4, 3])

In [ ]:
# Perform matrix multiplication  -- transpose!
mm_tensor = torch.matmul(trans_tensor, random_tensor_2)
mm_tensor

tensor([[0.8888, 0.8748, 0.8934, 0.3712],
        [0.5973, 0.6794, 0.4405, 0.3005],
        [1.0835, 0.9122, 0.9715, 0.4134],
        [0.5325, 0.3687, 0.2051, 0.2086]])

In [ ]:
## shape of new tensor
mm_tensor.shape

torch.Size([4, 4])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
rand_tensor_A = torch.rand(4,6)
rand_tensor_B = torch.rand(6,4)

# Matrix multiply tensors
mm_2 = torch.matmul(rand_tensor_A, rand_tensor_B)
mm_2

tensor([[2.2090, 1.6453, 2.5999, 1.6066],
        [2.4330, 1.2507, 2.3709, 2.1519],
        [2.3215, 1.5424, 2.4222, 2.1389],
        [1.7100, 0.9742, 1.8954, 1.2408]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
import torch

seed = 42

# Set the random seed for PyTorch CPU operations
torch.manual_seed(seed)

# If you are using CUDA, set the random seed for GPU operations
if torch.cuda.is_available():
  torch.cuda.manual_seed(seed)
  torch.cuda.manual_seed_all(seed)

# Set the deterministic flag for CuDNN (for deterministic behavior in some operations)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
RANDOM_SEED = 42
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

# Create two random tensors on GPU
rand_tensor = torch.rand(3,4).to(device)
rand_tensor_b = torch.rand(3,4).to(device)

print(rand_tensor)
print(rand_tensor_b)

tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])
tensor([[0.7749, 0.8208, 0.2793, 0.6817],
        [0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
mm_tensor = torch.matmul(rand_tensor.T, rand_tensor_b)
mm_tensor

tensor([[0.4441, 0.2671, 0.1937, 0.4865],
        [0.7094, 0.8909, 0.3640, 0.9950],
        [0.6872, 0.4858, 0.2846, 0.7083],
        [0.7554, 0.7797, 0.3576, 0.9467]])

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_result = torch.max(mm_tensor)

# Find min
min_result = torch.min(mm_tensor)

## print results
min_result, max_result

(tensor(0.1937), tensor(0.9950))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
mm_tensor

tensor([[0.4441, 0.2671, 0.1937, 0.4865],
        [0.7094, 0.8909, 0.3640, 0.9950],
        [0.6872, 0.4858, 0.2846, 0.7083],
        [0.7554, 0.7797, 0.3576, 0.9467]])

In [ ]:
# Find arg max
arg_max_res = torch.argmax(mm_tensor)

# Find arg min
arg_min_res = torch.argmin(mm_tensor)


## results
arg_max_res, arg_min_res

(tensor(7), tensor(2))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
seed = 42

# Create random tensor
rand_tensor = torch.rand([1,1,1,10])

# Remove single dimensions
new_tensor = torch.squeeze(rand_tensor)

# Print out tensors and their shapes
rand_tensor.shape, new_tensor.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))